# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - uses: actions/upload-artifact@v4
      with:
        path: ./
  
  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - uses: actions/download-artifact@v4
    - name: Create Release name
      id: release_name
      run : echo "RELEASE_NAME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
    - name: create zip
      run: zip -r app.zip . --exclude .funcignore
    - name: create release
      uses: softprops/action-gh-release@v2
      with:
        body: |
          Release ${{ steps.release_name.outputs.RELEASE_NAME }}
          This is an auto-generated release
        draft: false
        prerelease: false
        files: app.zip
        name: ${{ steps.release_name.outputs.RELEASE_NAME }}
        tag_name: ${{ steps.release_name.outputs.RELEASE_NAME }}
        generate_release_notes: true
        append_body: true
        make_latest: true
    
  
